In [1]:
import numpy as np

In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [9]:
np.ones(5,1)

TypeError: Cannot interpret '1' as a data type

In [10]:
np.ones((5,1))

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [11]:
np.zeros((7,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
x = np.ones((5,1))

In [15]:
y = np.zeros((5,1))

In [16]:
np.concatenate([x,y], axis = 1)

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [21]:
y_matrix = y.reshape(-1)
    y_matrix = np.eye(num_labels)[y_matrix]

IndentationError: unexpected indent (<ipython-input-21-4b9221bdf631>, line 2)

In [22]:
list1 = [[12],  
       [40],  
       [6],  
       [10]]  
  
# Creating 1-D Vertical Array  
y = np.array(list1)  
  
y = np.array(list1)  
  
print("We create a vector from a list:")  
print(y)  

We create a vector from a list:
[[12]
 [40]
 [ 6]
 [10]]


In [26]:
y_matrix = y.reshape(-1)

In [32]:
np.eye(41)[y_matrix]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.]])